CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    description text,
    status TEXT NOT NULL DEFAULT 'NEW',
    assignee BIGINT,
    CONSTRAINT fk_assignee
        FOREIGN KEY (assignee) REFERENCES users(id)
);